#specify the runtime e.g. go,node,java,.NET etc
runtime: go111

#Here we select the AppEngine Flex environment which performs a lot of the backend preparation for us including the ability to scale give the demand
env: standard

